---
# copyright Utrecht University

- name: Ensure PostgreSQL database is installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - postgresql
    - postgresql-contrib


- name: Ensure dependencies for Ansible PostgreSQL module are installed
  ansible.builtin.package:
    name: python3-psycopg2
    state: present


- name: Password protect loopback IPv4 connections
  ansible.builtin.lineinfile:
    dest: /etc/postgresql/12/main/pg_hba.conf
    regexp: 'host\s+all\s+all\s+127.0.0.1/32'
    line: 'host all all 127.0.0.1/32 md5'
  notify: Restart PostgreSQL


- name: Password protect loopback IPv6 connections
  ansible.builtin.lineinfile:
    dest: /etc/postgresql/12/main/pg_hba.conf
    regexp: 'host\s+all\s+all\s+::1/128'
    line: 'host all all ::1/128 md5'
  notify: Restart PostgreSQL


- name: Listen on all interfaces
  ansible.builtin.lineinfile:
    dest: /etc/postgresql/12/main/postgresql.conf
    line: "listen_addresses = '*'"
  notify: Restart PostgreSQL


- name: Ensure private key file is available for PostgreSQL
  ansible.builtin.command: 'cp {{ openssl_private_dir }}/{{ openssl_key_signed }} {{ openssl_key_signed }}'
  args:
    chdir: '/etc/postgresql/12/main'
    creates: '{{ openssl_key_signed }}'


- name: Ensure certificate file is available for PostgreSQL
  ansible.builtin.command: 'cp {{ openssl_certs_dir }}/{{ openssl_crt_signed }} {{ openssl_crt_signed }}'
  args:
    chdir: '/etc/postgresql/12/main'
    creates: '{{ openssl_crt_signed }}'


- name: Ensure PostgreSQL has access to PKI files
  ansible.builtin.file:
    path: '{{ item }}'
    mode: 0600
    group: 'postgres'
    owner: 'postgres'
    state: file
  with_items:
    - '/etc/postgresql/12/main/{{ openssl_key_signed }}'
    - '/etc/postgresql/12/main/{{ openssl_crt_signed }}'


- name: Ensure PostgreSQL is configured to use SSL
  community.general.ini_file:
    path: /etc/postgresql/12/main/postgresql.conf
    section: null
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    mode: 0644
  with_items:
    - option: ssl
      value: "on"
    - option: ssl_cert_file
      value: "'/etc/postgresql/12/main/{{ openssl_crt_signed }}'"
    - option: ssl_key_file
      value: "'/etc/postgresql/12/main/{{ openssl_key_signed }}'"
    - option: ssl_ciphers
      value: "'AES128+EECDH:AES128+EDH'"
  notify: Restart PostgreSQL


- name: Ensure PostgreSQL is enabled and started
  ansible.builtin.service:
    name: postgresql
    enabled: true
    state: started
