---
# copyright Utrecht University

- name: Ensure CKAN prerequisites are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - xml-commons
    - postgresql-server
    - postgresql-devel
    - postgresql
    - python-devel
    - libxslt
    - libxslt-devel
    - libxml2
    - libxml2-devel
    - python-virtualenv
    - gcc
    - gcc-c++
    - make
    - xalan-j2
    - unzip
    - policycoreutils-python
    - mod_wsgi
    - httpd


- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present


- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s


- user:
    name: ckan
    comment: "CKAN User"
    home: /usr/lib/ckan
    shell: /bin/bash
    groups: wheel
    append: yes


- name: Create CKAN database
  become_user: postgres
  become: yes
  postgresql_db:
    name: "ckan_default"
    encoding: UTF-8
    lc_collate: en_US.utf8
    lc_ctype: en_US.utf8
    template: template0


- name: Create CKAN database user
  become_user: postgres
  become: yes
  postgresql_user:
    db: "ckan_default"
    name: "ckan_default"
    password: "{{ ckan_database_password }}"
    priv: ALL


- name: Allow Apache to connect to Postgresql
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes


- name: Allow Apache to connect to Redis and SOLR
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes


- name: Allow Apache to listen on port 8983 for Solr
  seport:
    ports: 8888
    proto: tcp
    setype: http_port_t
    state: present


- name: Allow Apache to listen on port 6379 for Redis
  seport:
    ports: 6379
    proto: tcp
    setype: http_port_t
    state: present


- name: Ensure CKAN directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: ckan
  with_items:
    - /usr/lib/ckan
    - /usr/lib/ckan/default
    - /etc/ckan
    - /etc/ckan/default


- name: Run CKAN installation script
  become_user: ckan
  shell: |
    virtualenv --no-site-packages default
    . default/bin/activate
    pip install --upgrade pip
    pip install -U setuptools
    pip install --ignore-installed -e git+https://github.com/okfn/ckan.git@ckan-2.7.3#egg=ckan
    pip install --ignore-installed -r default/src/ckan/pip-requirements-docs.txt
    exit
    creates=/usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml
  register: ckan_installed


- name: Ensure CKAN config is present
  template:
    src: "development.ini.j2"
    dest: "/etc/ckan/default/development.ini"
  notify: Restart Apache webserver


- name: Ensure CKAN schema is symlinked in Solr
  become_user: root
  become: yes
  file:
    src: /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml
    dest: /var/solr/data/ckan/conf/schema.xml
    state: link
  register: link_schema


- name: Ensure defaultSearchField is not in Solr schema
  lineinfile:
    path: /var/solr/data/ckan/conf/schema.xml
    state: absent
    regexp: '^<defaultSearchField>text</defaultSearchField>$'
  notify: Restart Solr


- name: Ensure defaultOperator AND is not in Solr schema
  lineinfile:
    path: /var/solr/data/ckan/conf/schema.xml
    state: absent
    regexp: '^<solrQueryParser defaultOperator="AND"/>$'
  notify: Restart Solr


- name: Ensure CKAN who.ini is symlinked
  become_user: root
  become: yes
  file:
    src: /usr/lib/ckan/default/src/ckan/who.ini
    dest: /etc/ckan/default/who.ini
    state: link


- name: Install CKAN harvest extension
  become_user: root
  become: yes
  shell: |
    su -s /bin/bash - ckan
    cd /usr/lib/ckan
    . default/bin/activate
    pip install -e git+https://github.com/ckan/ckanext-harvest.git#egg=ckanext-harvest
    cd /usr/lib/ckan/default/src/ckanext-harvest/
    pip install -r pip-requirements.txt
    exit
    creates=/usr/lib/ckan/default/src/ckanext-harvest/
  notify: Restart Apache webserver


- name: Install CKAN OAI-PMH extension
  become_user: root
  become: yes
  shell: |
    su -s /bin/bash - ckan
    cd /usr/lib/ckan
    . default/bin/activate
    pip install -e git+https://github.com/andrmos/ckanext-oaipmh.git#egg=ckanext-oaipmh
    cd /usr/lib/ckan/default/src/ckanext-oaipmh/
    pip install -r requirements.txt
    python setup.py develop
    exit
    creates=/usr/lib/ckan/default/src/ckanext-oaipmh/
  notify: Restart Apache webserver


- name: Initialize CKAN database
  become_user: root
  become: yes
  shell: |
    su -s /bin/bash - ckan
    cd /usr/lib/ckan
    . default/bin/activate
    cd default/src/ckan
    paster db init -c /etc/ckan/default/development.ini
    paster --plugin=ckanext-harvest harvester initdb --config=/etc/ckan/default/development.ini
    exit
  when: ckan_installed.changed


- name: Add CKAN admin user
  become_user: ckan
  become: yes
  shell: |
    cd /usr/lib/ckan
    . default/bin/activate
    cd default/src/ckan
    paster user add ckanadmin password="{{ ckan_admin_password }}" email=ckanadmin@localhost name=ckanadmin -c /etc/ckan/default/development.ini
    paster sysadmin add ckanadmin -c /etc/ckan/default/development.ini
    exit
  when: ckan_installed.changed


- name: Add CKAN harvest user
  become_user: root
  become: yes
  shell: |
    cd /usr/lib/ckan
    . default/bin/activate
    cd default/src/ckan
    paster user add harvest password="{{ ckan_harvest_password }}" email=harvest@localhost name=harvest -c /etc/ckan/default/development.ini
    paster sysadmin add harvest -c /etc/ckan/default/development.ini
    exit
  when: ckan_installed.changed


- name: Ensure WSGI specification for CKAN is present
  template:
    src: "apache.wsgi.j2"
    dest: "/etc/ckan/default/apache.wsgi"
  notify: Restart Apache webserver


- name: Ensure EPOS-MSL virtual host config for Apache is present
  template:
    src: "epos-msl-vhost.conf.j2"
    dest: "/etc/httpd/conf.d/epos-msl-vhost.conf"
  notify: Restart Apache webserver
