---
# copyright Utrecht University

- name: Clone CKAN MSL util plugin
  ansible.builtin.git:
    repo: "https://github.com/utrechtuniversity/msl_ckan_util"
    dest: /usr/lib/ckan/msl_ckan_util
    version: "{{ ckan_msl_util_plugin_branch }}"
  when: ckan_plugins_editable_mode
  notify: Restart ckan-uwsgi


- name: Install CKAN MSL Util plugin
  ansible.builtin.pip:
    name: "git+https://github.com/UtrechtUniversity/msl_ckan_util@{{ ckan_msl_util_plugin_branch }}"
    virtualenv: /usr/lib/ckan/default
    extra_args: "--upgrade"
  notify: Restart ckan-uwsgi


- name: Install CKAN MSL Util plugin (editable mode)
  ansible.builtin.pip:
    name: /usr/lib/ckan/msl_ckan_util
    virtualenv: /usr/lib/ckan/default
    extra_args: "-e"
  when: ckan_plugins_editable_mode
  notify: Restart ckan-uwsgi
