---
# copyright Utrecht University

- name: Clone scheming CKAN plugin
  ansible.builtin.git:
    repo: "https://github.com/ckan/ckanext-scheming"
    dest: /usr/lib/ckan/ckanext-scheming
    version: "{{ ckanext_scheming_version }}"
  notify: Restart ckan-uwsgi


- name: Install CKAN scheming plugin (regular mode)
  ansible.builtin.pip:
    name: "https://github.com/ckan/ckanext-scheming/archive/{{ ckanext_scheming_version }}.tar.gz"
    virtualenv: /usr/lib/ckan/default
    extra_args: "--upgrade"
  when: not ckan_plugins_editable_mode
  notify: Restart ckan-uwsgi


- name: Install CKAN scheming plugin (editable mode)
  ansible.builtin.pip:
    name: /usr/lib/ckan/ckanext-scheming
    virtualenv: /usr/lib/ckan/default
    extra_args: "-e"
  when: ckan_plugins_editable_mode
  notify: Restart ckan-uwsgi
