version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    allow:
      - update-types: ["version-update:semver-major"]
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    cooldown:
      default-days: 7
