---
# copyright Utrecht University
# This playbook deploys a complete EPOS-MSL CKAN instance.

- hosts: all
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full | version_compare('2.4', '>=')"
        msg: >
          "You must update Ansible to at least 2.4 to deploy EPOS CKAN."


- name: Provision EPOS-MSL CKAN server
  hosts: all
  become: yes
  roles:
    - common
    - certificates
    - apache
    - postgresql
    - solr
    - redis
    - ckan
