---
collections:
  - name: community.general
    version: 4.7.0
  - name: community.crypto
    version: 1.9.6
  - name: community.mysql
    version: 2.3.1
  - name: community.postgresql
    version: 1.5.0
  - name: ansible.posix
    version: 1.4.0
