---
collections:
  - name: community.general
    version: 3.8.1
  - name: community.crypto
    version: 1.9.6
  - name: community.mysql
    version: 2.3.1
  - name: community.postgresql
    version: 1.5.0
