---
# copyright Utrecht University
# This playbook provisions EPOS-MSL instance with the Zabbix agent, PostgreSQL monitoring and Zabbix user access to the database.

- hosts: localhost
  gather_facts: False
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full is version('2.7', '>=')"
        msg: >
          "You must update Ansible to at least 2.7 to deploy EPOS-MSL CKAN."


- name: Provision EPOS-MSL CKAN server with Zabbix monitoring
  hosts: all
  become: yes
  roles:
    - zabbix-agent
    - role: zabbix-postgresql
      zabbix_database_name: "{{ ckan_database_name }}"
    - zabbix-ckan
