---
# copyright Utrecht University

galaxy_info:
  author: Sietse Snel
  description: Install Docker Compose
  license: GPLv3
  min_ansible_version: '2.11'
  platforms:
    - name: EL
      version: 9
