---
# copyright Utrecht University

- name: Ensure group for EPOS-MSL docker setup exists
  ansible.builtin.group:
    name: "{{ epos_msl_user }}"


- name: Ensure user for EPOS-MSL docker setup exists
  ansible.builtin.user:
    name: "{{ epos_msl_user }}"
    group: "{{ epos_msl_user }}"
    groups: docker
    create_home: true


- name: Check out EPOS-MSL repo with Docker Compose setup
  become_user: "{{ epos_msl_user }}"
  become: true
  ansible.builtin.git:
    repo: "https://github.com/UtrechtUniversity/epos-msl.git"
    dest: "/home/{{ epos_msl_user }}/epos-msl"
    version: "{{ epos_msl_branch }}"
    force: true


- name: Install configuration Docker Compose setup
  ansible.builtin.template:
    src: env.j2
    dest: "/home/{{ epos_msl_user }}/epos-msl/docker/.env"
    owner: '{{ epos_msl_user }}'
    group: '{{ epos_msl_user }}'
    mode: '0644'


- name: Open TCP port for EPOS MSL catalog
  ansible.posix.firewalld:
    port: "{{ epos_msl_host_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  become: true


- name: Create EPOS-MSL systemd unit file
  ansible.builtin.template:
    src: epos-msl.service.j2
    dest: /etc/systemd/system/epos-msl.service
    owner: root
    group: root
    mode: '0644'


- name: Enable and start EPOS-MSL service
  ansible.builtin.service:
    name: epos-msl
    enabled: true
    state: started
    daemon_reload: true
