---
# copyright Utrecht University

# Call command, rather than module, because module doesn't work
# right on Ubuntu 20.04
- name: Reload Supervisor # noqa command-instead-of-module
  ansible.builtin.command: supervisorctl reload


# Call command, rather than module, because module doesn't work
# right on Ubuntu 20.04
- name: Restart ckan-uwsgi # noqa command-instead-of-module
  ansible.builtin.command: supervisorctl restart ckan-uwsgi:ckan-uwsgi-00


- name: Restart Nginx webserver
  ansible.builtin.service:
    name: nginx
    state: restarted
