---
# copyright Utrecht University

# This installs an old version of Solr that comes with a native Ubuntu package,
# rather than a version from Solr.org
solr_install_native: true

# CKAN 2.9 only supports Solr 7 and 8. This playbook uses the Solr 8 CKAN schema,
# so it only works with Solr 8.x The settings below only take effect when solr_install_native
# has been disabled.
#
# After upgrading from Solr 3 to Solr 8, you will need to manually rebuild indexes:
# $ sudo systemctl restart solr
# $ sudo -iu ckan /usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini search-index build -r
solr_version: "8.11.3"
solr_checksum: sha512:10f09b163bd9c31b2a8fdf889cf624114648e76881d69a4c096d473272c47b3cbe37ec9f9bd1980fd90967352c4052477065e165127eccb2c49a60c8d9860afc

solr_config_dir: "/var/solr/data/ckan/conf"
solr_schema_filename: "schema.xml"
solr_elevate_example_dir: "/opt/solr-{{ solr_version }}/server/solr/configsets/sample_techproducts_configs/conf"

# Other settings
solr_port: 8983
