---
# copyright Utrecht University

msl_api_version: 1.5.2
msl_api_database: mslapi
msl_api_database_user: msl
msl_api_user: www-data
msl_api_worker_logdir: /var/www/msl_api

composer_version: 2.5.4
composer_checksum: sha256:91ce6cbf9463eae86ae9d5c21d42faa601a519f3fbb2b623a55ee24678079bd3

# Parameters without default value
# msl_api_database_password: msl
# msl_api_app_key
# msl_api_app_url
# msl_api_asset_url
# ckan_api_token
