---
# copyright Utrecht University

- name: Install old version of Solr using distribution-native package
  ansible.builtin.import_tasks: install-native-solr.yml
  when: solr_install_native


- name: Install Solr 8 from official package
  ansible.builtin.import_tasks: install-solr8.yml
  when: not solr_install_native
