---
# copyright Utrecht University

- name: Ensure Solr is installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - solr-tomcat


- name: Install Solr server configuration
  ansible.builtin.template:
    src: templates/server.xml.j2
    dest: /etc/tomcat9/server.xml
    owner: root
    group: tomcat
    mode: 0640
  register: serverxml


# Restarting Solr immediately so that it runs on the right port. If
# we would use the handler, CKAN wouldn't be able to find Solr.
- name: Restart Solr if config if server configuration changed
  service:
    name: tomcat9
    state: restarted
  when: serverxml.changed


- name: Ensure Solr is enabled on boot
  service:
    name: tomcat9
    enabled: true
