---
# copyright Utrecht University

- name: Ensure Ansible and other dependencies are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - acl
    - git
    - python3-pip
