---
# copyright Utrecht University

- name: Ensure Ansible dependencies are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
  - libsemanage-python
  - libselinux-python
  - policycoreutils-python


- name: Ensure basics (vim, bind-utils, etc.) are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - bind-utils
    - vim
    - htop
    - git
    - tmux
