---
# copyright Utrecht University

- name: Ensure Ansible dependencies are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - acl
    - python3-pip
    - python3-selinux
    - policycoreutils-python-utils
