---
# copyright Utrecht University

- name: Ensure firewall is installed
  package:
    name: firewalld
    state: present
  notify: Restart firewall


- name: Ensure firewall is running and enabled
  service:
    name: firewalld
    state: started
    enabled: yes
