---
# copyright Utrecht University

- name: Update systemd-resolved config to use Google DNS servers
  ansible.builtin.copy:
    src: files/resolved.conf
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart systemd-resolved


- name: Flush handlers for immediate effect of changing DNS configuration
  ansible.builtin.meta: flush_handlers
