---
# copyright Utrecht University

- name: Install MSL-API prerequisites
  ansible.builtin.import_tasks: prerequisites.yml
- name: Configure MSL-API database
  ansible.builtin.import_tasks: database.yml
- name: Install MSL-API application
  ansible.builtin.import_tasks: application.yml
- name: Ensure MSL-API storage directory is present
  ansible.builtin.import_tasks: storage.yml
- name: Configure MSL-API
  ansible.builtin.import_tasks: config.yml
- name: Add self-signed certificate to CA certificate file on development
  ansible.builtin.import_tasks: update-cacerts.yml
  when: epos_msl_environment == "development"
