---
# copyright Utrecht University

- name: Add Ondrej PHP repository for old versions of PHP
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php


- name: Ensure MSL API prerequisites are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - php8.0
    - php8.0-bcmath
    - php8.0-common
    - php8.0-curl
    - php8.0-fpm
    - php8.0-gd
    - php8.0-mbstring
    - php8.0-mysql
    - php8.0-xml
    - php8.0-zip

- name: Install Composer version needed for current version of MSL-API
  ansible.builtin.get_url:
    url: "https://getcomposer.org/download/{{ composer_version }}/composer.phar"
    dest: /usr/local/bin/composer2
    checksum: '{{ composer_checksum }}'
    group: root
    owner: root
    mode: "0755"
