---
# copyright Utrecht University


- name: Download Zabbix source code for PostgreSQL monitoring files
  ansible.builtin.get_url:
    url: 'https://github.com/zabbix/zabbix/archive/refs/tags/{{ zabbix_source_version }}.tar.gz'
    dest: '/tmp/zabbix-{{ zabbix_source_version }}.tar.gz'


- name: Extract Zabbix source code
  ansible.builtin.unarchive:
    src: '/tmp/zabbix-{{ zabbix_source_version }}.tar.gz'
    dest: /usr/src
    remote_src: true


- name: Create Zabbix postgresql directory
  ansible.builtin.file:
    path: '{{ item }}'
    owner: zabbix
    group: zabbix
    mode: 0755
    state: directory
  with_items:
    - /var/lib/zabbix
    - /var/lib/zabbix/postgresql


- name: Synchronize Zabbix Postgresql files
  ansible.posix.synchronize:
    src: '/usr/src/zabbix-{{ zabbix_source_version }}/templates/db/postgresql/postgresql/'
    dest: /var/lib/zabbix/postgresql
  delegate_to: "{{ inventory_hostname }}"


# We use a template with hardcoded values for the Zabbix database user, password
# and database, because the server-side PostgreSQL monitoring template passes these parameters
# in a different order than the upstream PostgreSQL client template for Zabbix 5.0.
- name: Load Zabbix Postgresql template
  ansible.builtin.template:
    src: template_db_postgresql.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf.d/template_db_postgresql.conf
    owner: zabbix
    group: zabbix
    mode: 0640
  no_log: true


- name: Create Zabbix database user
  become_user: postgres
  become: true
  postgresql_user:
    db: "{{ zabbix_database_name }}"
    name: "{{ zabbix_psql_monitoring_user }}"
    password: "{{ zabbix_psql_monitoring_password }}"
    priv: "CONNECT"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE


- name: Grant Zabbix user select rights on postgres database
  become: true
  become_user: postgres
  postgresql_privs:
    db: "{{ zabbix_psql_monitoring_db }}"
    role: "{{ zabbix_psql_monitoring_user }}"
    objs: ALL_IN_SCHEMA
    privs: SELECT
